[tool.poetry]
name = "pcdcanalysistools"
version = "0.1.12"
description = "microservice analysis tools"
authors = ["Your Name <you@example.com>"]
license = "Apache License 2.0"

[tool.poetry.dependencies]
# needs a higher python version (3.8) than the other microservices (3.6) because of
# min requirements for lifelines, pandas, and numpy
python = "^3.8"
pycryptodome = "3.9.8"
pcdcutils = {git = "https://github.com/chicagopcdc/pcdcutils.git", rev = "0.1.1"}


[tool.poetry.dev-dependencies]
pytest = "^4.6.5"
pytest-cov = "2.5.1"
requests_mock = "1.4.0"
httmock = "1.2.3"
lockfile = "0.12.2"
coverage = "4.0.0"
mock = "1.0.1"
pytest-flask = "0.15.0"
moto = "0.4.5"
sphinxcontrib-httpdomain = "1.3.0"
codacy-coverage = "^1.3.11"
sphinx-rtd-theme = "^1.0.0"
Sphinx = "3.0.4"
flasgger = "0.9.1"
cdisutilstest = {git = "https://git@github.com/uc-cdis/cdisutils-test.git", rev = "1.0.0"}
authlib = "^0.14.2"
authutils = "4.0.0"
Flask = "^1.1.4"
Werkzeug = "^0.16.0"
jsonschema = "2.5.1"
cdislogging = "^1.1.1"
indexclient = {git = "https://github.com/uc-cdis/indexclient.git", rev = "1.6.0"}
hsclient = {git = "https://github.com/uc-cdis/hsclient.git", rev = "1.0.0"}
gen3authz = "^0.4.0"
cdispyutils = "1.0.4"
fuzzywuzzy = "^0.6.1"
lxml = "4.6.3"
simplejson = "^3.8.1"
gen3rbac = "0.1.2"
doiclient = {git = "https://git@github.com/uc-cdis/doiclient.git", rev = "1.0.0"}
numpy = "^1.17.3"
scipy = "^1.3.1"
pandas = "1.3.4"
lifelines = "^0.25.2"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
